/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_sunflyer_simpnk_control_DialWindows */

#ifndef _Included_cn_sunflyer_simpnk_control_DialWindows
#define _Included_cn_sunflyer_simpnk_control_DialWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_sunflyer_simpnk_control_DialWindows
 * Method:    Dial
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sunflyer_simpnk_control_DialWindows_Dial
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     cn_sunflyer_simpnk_control_DialWindows
 * Method:    HeartBeat
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_cn_sunflyer_simpnk_control_DialWindows_HeartBeat
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     cn_sunflyer_simpnk_control_DialWindows
 * Method:    getDialResult
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_sunflyer_simpnk_control_DialWindows_getDialResult
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
