/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cqxinli_ClickDial */

#ifndef _Included_cqxinli_ClickDial
#define _Included_cqxinli_ClickDial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cqxinli_ClickDial
 * Method:    dialRasWindows
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cqxinli_ClickDial_dialRasWindows
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cqxinli_ClickDial
 * Method:    dialRasWindowsErrorStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cqxinli_ClickDial_dialRasWindowsErrorStr
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
